# This workflow will build and push a node.js application to an Azure Web App on every push to the master branch.
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE with the value of your Azure publish profile.
#
# 2. Change the values for the AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables  (below).
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on:
  push:
    branches:
      - master
    paths:
      - 'src/client/**'

env:
  AZURE_WEBAPP_NAME: madsdappwks    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './src/client'      # set this to the path to your web app project, defaults to the repository root
  PUBLISH_OUTPUT_PATH: './client'
  DOTNET_VERSION: '3.1.100'                # set this to the dotnet version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Build with dotnet
      run: |
        dotnet build --configuration Release ${{env.AZURE_WEBAPP_PACKAGE_PATH}}       
    - name: Publish with dotnet
      run: |
        dotnet publish --configuration Release --self-contained -r linux-x64 -o PUBLISH_OUTPUT_PATH ${{env.AZURE_WEBAPP_PACKAGE_PATH}}       
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: PUBLISH_OUTPUT_PATH
